# Generated by Django 6.0.3 on 2026-03-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Company',
            new_name='company',
        ),
    ]
